---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: Group Client Certificate Extraction
    category: Security
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default