apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-large-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: install-tools
spec:
  workspaces:
    - name: shared-home
  steps:
    - name: setup-and-install
      image: registry.access.redhat.com/ubi8/nodejs-20
      script: |
        #!/bin/sh
        set -e
        export HOME=/workspace/shared-home

        echo "📁 Listing shared-home contents:"
        ls -al /workspace/shared-home
        

        echo "📁 Creating npm-global directory"
        mkdir -p /workspace/shared-home/npm-global
        ls -al /workspace/shared-home/npm-global

        echo "📦 Configuring npm"
        npm config set prefix /workspace/shared-home/npm-global
        export PATH="/workspace/shared-home/npm-global/bin:$PATH"

        echo "⬇️ Installing Anypoint CLI"
        npm install -g anypoint-cli-v4

        echo "🔌 Installing Anypoint plugin"
        anypoint-cli-v4 plugins:install anypoint-cli-pdk-plugin

        echo "✅ Versions:"
        node -v
        npm -v
        anypoint-cli-v4 --version

    - name: install-rust
      image: registry.access.redhat.com/ubi8/nodejs-20
      script: |
        #!/bin/sh
        set -e
        export HOME=/workspace/shared-home
        export PATH="/workspace/shared-home/npm-global/bin:$PATH"
        
        echo "🔧 Verifying Anypoint CLI"
        echo "npm-global"
        ls -la /workspace/shared-home
        echo "npm-global"
        ls -la /workspace/shared-home/npm-global/
         echo ".npm"
        ls -la /workspace/shared-home/.npm/
        /workspace/shared-home/.npm/bin/anypoint-cli-v4 --version || echo "Not found!"

        echo "🛠 Installing curl and git"
        microdnf install -y curl git ca-certificates

        echo "🌐 Configuring custom CA (if needed)"
        export SSL_CERT_FILE=/etc/ssl/custom-ca/ca.crt

        echo "⬇️ Installing Rust"
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . "$HOME/.cargo/env"

        rustc --version
        rustup default 1.83.0
        rustup target add wasm32-wasi
        cargo install --locked cargo-generate@0.22.0

        echo "🌍 Anypoint CLI configuration"
        export ANYPOINT_HOST=eu1.anypoint.mulesoft.com
        anypoint-cli-v4 conf client_id bbAZAZ
        anypoint-cli-v4 conf client_secret 3ZAZAz
        anypoint-cli-v4 conf organization 8ZAZAZAZ
        anypoint-cli-v4 account:environment:list

      volumeMounts:
        - name: custom-ca
          mountPath: /etc/ssl/custom-ca
          readOnly: true
      env:
        - name: SSL_CERT_FILE
          value: /etc/ssl/custom-ca/ca.crt
  volumes:
    - name: custom-ca
      configMap:
        name: rust-certificate
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tools-install-pipeline
spec:
  workspaces:
    - name: shared-home
  tasks:
    - name: install-all
      taskRef:
        name: install-tools
      workspaces:
        - name: shared-home
          workspace: shared-home
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: tools-install-run
spec:
  pipelineRef:
    name: tools-install-pipeline
  taskRunTemplate:
    serviceAccountName: sa-docker
  workspaces:
    - name: shared-home
      persistentVolumeClaim:
        claimName: pvc-large-storage
