---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  labels:
    title: Group Payload Message Logging Policy
    category: compliance
    metadata/interfaceScope: api,resource
spec:
  extends:
    - name: extension-definition
      namespace: default
