# Copyright 2024 AXA. All rights reserved.
version: "3.3"

services:
  local-flex:
    image: mulesoft/flex-gateway:1.10.1
    environment:
        - "FLEX_ENVOY_HEADERS_ENABLED=true"
    ports:
      - 8083:8084
    volumes:
      - ./config:/usr/local/share/mulesoft/flex-gateway/conf.d/