# Copyright 2023 Salesforce, Inc. All rights reserved.
[package]
name = "antimalware_scanning"
version = "1.1.0"
rust-version = "1.87.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.anypoint]
group_id = "fa8e8050-81d8-477a-a4c3-0c4f25df8525"
definition_asset_id = "group-antimalware-scanning"
implementation_asset_id = "antimalware-scanning-flex"

[dependencies]
pdk = { version = "1.4.0", registry = "anypoint" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
anyhow = "1.0"
json = "0.12.4"
#chrono = {version = "0.4.26", features = ["serde"] }
multer = "3.1.0"
futures = "0.3.31"
bytes = "1.10.1"
log = "0.4"
chrono = "0.4.19"
regex = "1.5"
url = "2.5"

[dev-dependencies]
pdk-test = { version = "1.2", registry = "anypoint" }
httpmock = "0.6"
reqwest = "0.11"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
strip = "debuginfo"
