# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http-2
spec:
  address: http://0.0.0.0:8087
  services:
    upstream:
      address: http://host.docker.internal:8089
      routes:
        - config:
            destinationPath: /

 