# Copyright 2023 Salesforce, Inc. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http
spec:
  address: http://0.0.0.0:8084
  services:
    upstream:
      address: http://backend
      routes:
        - config:
            destinationPath: /anything/echo/
  policies:
    - policyRef:
        name: group-antimalware-scan-saas-flex-v1-0 # This value will be overriden during 'make run' execution
        namespace: default
      # Fill the config with a policy configuration that matches the schema specified in the policy
      # definition gcl.yaml. Eg:
      # config:
      #   someProperty: desiredValue
      config:
        host: http://localhost:8087
        userName: name
        name: service
        password: pass
        authPath: /file
        namespace: default
        scanPath: /file
