# Copyright 2024 AXA. All rights reserved.
---
apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: ingress-http

spec:
  address: http://0.0.0.0:8084
  services:
    upstream:
      #address: http://sse.dev
      address: http://host.docker.internal:8089
      #address: https://petstore.swagger.io/v2/pet/1
      routes:
        - config:
            destinationPath: /
  policies:
    - policyRef:
        name: group-message-logging-policy-v1-0-impl
          # Fill the config with a policy configuration that matches the schema specified in the policy
          # definition gcl.yaml. Eg:
          # config:
          #   someProperty: desiredValue
        namespace: default

# ---
# apiVersion: gateway.mulesoft.com/v1alpha1
# kind: PolicyBinding
# metadata:
#   name: message-logging-flex
#   namespace: gateway
# spec:
#   targetRef:
#     name: ingress-http
#   policyRef:
#     name: message-logging-flex
#     namespace: default
#   config:
#     loggingConfiguration:
#       - itemName: "Config 1"
#         itemData:
#           message: "#[payload]"
#           level: "DEBUG"
#           firstSection: true
#           secondSection: true
